# Generated by Django 6.0.2 on 2026-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Deployment Logs (Work)'), ('edu', 'Knowledge Base (Education)')], max_length=10)),
                ('title_en', models.CharField(max_length=150)),
                ('organization_en', models.CharField(max_length=150)),
                ('details_en', models.TextField(help_text='استخدم علامة | للفصل بين النقاط')),
                ('title_ar', models.CharField(max_length=150)),
                ('organization_ar', models.CharField(max_length=150)),
                ('details_ar', models.TextField(help_text='استخدم علامة | للفصل بين النقاط')),
                ('period', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: HealthLink.cs', max_length=100)),
                ('title_en', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('title_ar', models.CharField(max_length=200)),
                ('description_ar', models.TextField()),
                ('tech_stack', models.CharField(help_text='مثال: C# أو Python', max_length=50)),
                ('code_snippet', models.TextField(help_text='أدخل كود HTML الخاص بتنسيق الألوان هنا')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_en', models.CharField(default="ALHANOUF <br> <span class='text-[#EB3678]'>ALLUHAYDAN</span>", max_length=200)),
                ('hero_desc_en', models.TextField(default='Architecting high-performance digital ecosystems...')),
                ('hero_title_ar', models.CharField(default="الهنوف <br> <span class='text-[#EB3678]'>اللحيدان</span>", max_length=200)),
                ('hero_desc_ar', models.TextField(default='هندسة النظم الرقمية عالية الأداء باستخدام...')),
                ('contact_desc_en', models.TextField(default='Ready to architect the next big thing?')),
                ('contact_desc_ar', models.TextField(default='هل أنت مستعد لبناء المشروع العظيم القادم؟')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global Site Settings',
                'verbose_name_plural': 'Global Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks'), ('data', 'Data Stack'), ('systems', 'Systems')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
