# Generated by Django 6.0.2 on 2026-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='alhanoufkhalaf1@gmail.com', help_text='الإيميل الذي سيظهر للزوار', max_length=254),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Languages', '01. Core Languages'), ('Web Architecture', '02. Web Architecture'), ('Data Intelligence', '03. Data Intelligence'), ('Infrastructure', '04. Infrastructure & Tools')], max_length=20),
        ),
    ]
